CREATE TABLE MEMBER(
   MID VARCHAR(20) PRIMARY KEY,
   MPW VARCHAR(20) NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   ROLE VARCHAR(10) NOT NULL
);



SELECT * FROM USER_TABLES;
SELECT * FROM MEMBER;
DROP TABLE CAR;
DROP TABLE CMEMBER;
DROP TABLE CBOARD;
DROP TABLE CREPLY;
DROP TABLE BOARD;
DROP TABLE MEMBER;
DROP TABLE REPLY;
INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN');